/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tpmod13;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author LOQ
 */
public class CrudMahasiswa extends javax.swing.JFrame {
public DefaultListModel model = new DefaultListModel();
private java.sql.Connection conn; // sengaja kaya gini soalnya namanya sama
    /**
     * Creates new form CrudMahasiswa
     */
    public CrudMahasiswa() {
        initComponents();
        list_data.setModel(model);
        this.conn = Connection.getConnection();
        btn_update.setEnabled(false);
        //this.GetData();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        tab_controls = new javax.swing.JTabbedPane();
        pane_tables = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list_data = new javax.swing.JList<>();
        btn_update_data = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        label_nama = new javax.swing.JLabel();
        label_nim = new javax.swing.JLabel();
        label_prodi = new javax.swing.JLabel();
        btn_edit = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        pane_inputs = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        input_nim = new javax.swing.JTextField();
        input_nama = new javax.swing.JTextField();
        radio_if = new javax.swing.JRadioButton();
        radio_se = new javax.swing.JRadioButton();
        radio_it = new javax.swing.JRadioButton();
        radio_ds = new javax.swing.JRadioButton();
        btn_save = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        list_data.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        list_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                list_dataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(list_data);

        btn_update_data.setText("Perbarui Daftar");
        btn_update_data.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_update_dataActionPerformed(evt);
            }
        });

        jLabel5.setText("NIM :");

        jLabel6.setText("Nama :");

        jLabel7.setText("Prodi :");

        jLabel8.setText("Detail_mahasiswa");

        label_nama.setText("blank");

        label_nim.setText("blank");

        label_prodi.setText("blank");

        btn_edit.setText("edit");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_hapus.setText("hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pane_tablesLayout = new javax.swing.GroupLayout(pane_tables);
        pane_tables.setLayout(pane_tablesLayout);
        pane_tablesLayout.setHorizontalGroup(
            pane_tablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_tablesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pane_tablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pane_tablesLayout.createSequentialGroup()
                        .addComponent(btn_update_data)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_edit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_hapus))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pane_tablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pane_tablesLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_nama))
                    .addGroup(pane_tablesLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(label_prodi))
                    .addGroup(pane_tablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pane_tablesLayout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(18, 18, 18)
                            .addComponent(label_nim))
                        .addComponent(jLabel8)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        pane_tablesLayout.setVerticalGroup(
            pane_tablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_tablesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pane_tablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pane_tablesLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addGroup(pane_tablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_update_data)
                            .addComponent(btn_hapus)
                            .addComponent(btn_edit)))
                    .addGroup(pane_tablesLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(15, 15, 15)
                        .addGroup(pane_tablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(label_nim))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pane_tablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(label_nama))
                        .addGap(19, 19, 19)
                        .addGroup(pane_tablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(label_prodi))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        tab_controls.addTab("Daftar Mahasiswa", pane_tables);

        jLabel1.setText("NIM :");

        jLabel2.setText("Nama :");

        jLabel3.setText("jLabel1");

        jLabel4.setText("Prodi :");

        buttonGroup1.add(radio_if);
        radio_if.setText("IF");

        buttonGroup1.add(radio_se);
        radio_se.setText("SE");

        buttonGroup1.add(radio_it);
        radio_it.setText("IT");

        buttonGroup1.add(radio_ds);
        radio_ds.setText("DS");

        btn_save.setText("Simpan");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_update.setText("update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pane_inputsLayout = new javax.swing.GroupLayout(pane_inputs);
        pane_inputs.setLayout(pane_inputsLayout);
        pane_inputsLayout.setHorizontalGroup(
            pane_inputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_inputsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pane_inputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pane_inputsLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addComponent(input_nim, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pane_inputsLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(input_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pane_inputsLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(pane_inputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pane_inputsLayout.createSequentialGroup()
                                .addComponent(radio_if)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(radio_se))
                            .addGroup(pane_inputsLayout.createSequentialGroup()
                                .addComponent(radio_it)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pane_inputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pane_inputsLayout.createSequentialGroup()
                                        .addComponent(btn_save)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn_update))
                                    .addComponent(radio_ds))))))
                .addContainerGap(137, Short.MAX_VALUE))
            .addGroup(pane_inputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pane_inputsLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jLabel3)
                    .addContainerGap(369, Short.MAX_VALUE)))
        );
        pane_inputsLayout.setVerticalGroup(
            pane_inputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pane_inputsLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pane_inputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(input_nim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pane_inputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(input_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(pane_inputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(radio_if)
                    .addComponent(radio_se))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pane_inputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio_it)
                    .addComponent(radio_ds))
                .addGap(39, 39, 39)
                .addGroup(pane_inputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save)
                    .addComponent(btn_update))
                .addContainerGap(68, Short.MAX_VALUE))
            .addGroup(pane_inputsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pane_inputsLayout.createSequentialGroup()
                    .addGap(94, 94, 94)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(191, Short.MAX_VALUE)))
        );

        tab_controls.addTab("Input Masiswa", pane_inputs);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab_controls)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tab_controls)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_update_dataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_update_dataActionPerformed
        // TODO add your handling code here:
        try{
            this.GetData();
        }catch(Exception e){
              Logger.getLogger(e.getMessage());
        }
        
    }//GEN-LAST:event_btn_update_dataActionPerformed

    private void list_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_dataMouseClicked
        // TODO add your handling code here:
        String[] str = list_data.getSelectedValue().split(" ");
        label_nim.setText(str[0]);
        label_nama.setText(str[1]);
        label_prodi.setText(str[2]);
    }//GEN-LAST:event_list_dataMouseClicked

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        String nim = input_nim.getText();
        String nama = input_nama.getText();
        String radio = "";
        if(radio_if.isSelected()){
          radio = "IF";
        }else if (radio_se.isSelected()){
          radio = "SE";
        }else if(radio_it.isSelected()){
          radio = "IT";
        }else if(radio_ds.isSelected()){
          radio = "DS";
        }
         try{
           PreparedStatement pr = conn.prepareStatement("INSERT INTO mhs (nim,nama,prodi) VALUES(?,?,?)");
           pr.setString(1, nim);
           pr.setString(2, nama);
           pr.setString(3, radio);
           int rowInserted = pr.executeUpdate(); // buat updatenta
            if(rowInserted > 0){
                JOptionPane.showMessageDialog(this, "data berhasil di tambahkan");
                input_nim.setText("");
                input_nama.setText("");
                radio_if.setSelected(false);
                radio_se.setSelected(false);
                radio_it.setSelected(false);
                radio_ds.setSelected(false);
            }
         }catch(SQLException e){
           Logger.getLogger(e.getMessage()).log(Level.INFO, null, e); // buat info
         }
      
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        // TODO add your handling code here:
         
         try{
             String[] str = list_data.getSelectedValue().split(" ");
            if(str == null){
                 throw new Exception("silahkan memiliki tab");
            }
         String nim = str[0];
            String sql = "DELETE FROM mhs WHERE nim ="+nim+";";
            PreparedStatement st = conn.prepareStatement(sql);
            int output = st.executeUpdate();
            this.model.clear();
            this.GetData();
            if (output > 0){
                JOptionPane.showMessageDialog(this, "data berhasil di hapus");
            } 
         }catch(SQLException e){
             JOptionPane.showMessageDialog(this, e.getMessage());
         }catch(Exception e){
              JOptionPane.showMessageDialog(this, e.getMessage());
         }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        // TODO add your handling code here:
        try{
            btn_update.setEnabled(true);
            btn_save.setEnabled(false);
            tab_controls.setSelectedIndex(1); // set tabbpane 
            String[] str = list_data.getSelectedValue().split(" ");
            input_nim.setText(str[0]);
            input_nama.setText(str[1]);
            switch(str[2]){
                case "IF":
                    radio_if.setSelected(true);
                   break;
                case "SE":
                    radio_se.setSelected(true);
                   break;
                case "IT":
                    radio_it.setSelected(true);
                   break;
                case "DS":
                    radio_ds.setSelected(true);
                   break;
            }
            
        }catch(Exception e){
        
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:\
      
        String nim = input_nim.getText();
        String nama = input_nama.getText();
        String radio = "";
        if(radio_if.isSelected()){
          radio = "IF";
        }else if (radio_se.isSelected()){
          radio = "SE";
        }else if(radio_it.isSelected()){
          radio = "IT";
        }else if(radio_ds.isSelected()){
          radio = "DS";
        }
         try{
           PreparedStatement pr = conn.prepareStatement("UPDATE mhs set nim = ? , nama = ? , prodi = ? where nim = ?");
           pr.setString(1, nim);
           pr.setString(2, nama);
           pr.setString(3, radio);
           pr.setString(4, nim);
           int rowInserted = pr.executeUpdate(); // buat updatenta
            if(rowInserted > 0){
                JOptionPane.showMessageDialog(this, "data berhasil di update");
                input_nim.setText("");
                input_nama.setText("");
                radio_if.setSelected(false);
                radio_se.setSelected(false);
                radio_it.setSelected(false);
                radio_ds.setSelected(false);
                // button and view  management
                btn_update.setEnabled(false);
                btn_save.setEnabled(true);
                tab_controls.setSelectedIndex(0); // set tabbpane 
                this.GetData(); // get data again
            }
         }catch(SQLException e){
           Logger.getLogger(e.getMessage()).log(Level.INFO, null, e); // buat info
         }
    }//GEN-LAST:event_btn_updateActionPerformed
    public void GetData(){
        try{
            String sql = "SELECT * FROM mhs";
            PreparedStatement st = conn.prepareStatement(sql);
            ResultSet output = st.executeQuery();
            this.model.clear();
            while(output.next()){ // loop result set nya
                this.model.addElement(output.getString("nim") +" "+ output.getString("nama") +" "+ output.getString("prodi") );
            }
            
        }catch(SQLException e){
            Logger.getLogger(e.getMessage()).log(Level.INFO, null, e); // buat info
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrudMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_update;
    private javax.swing.JButton btn_update_data;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField input_nama;
    private javax.swing.JTextField input_nim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label_nama;
    private javax.swing.JLabel label_nim;
    private javax.swing.JLabel label_prodi;
    private javax.swing.JList<String> list_data;
    private javax.swing.JPanel pane_inputs;
    private javax.swing.JPanel pane_tables;
    private javax.swing.JRadioButton radio_ds;
    private javax.swing.JRadioButton radio_if;
    private javax.swing.JRadioButton radio_it;
    private javax.swing.JRadioButton radio_se;
    private javax.swing.JTabbedPane tab_controls;
    // End of variables declaration//GEN-END:variables
}
